"""Demo packager — assembles existing pipeline output into a presentable sales demo folder.

Read-only: never regenerates content. Discovers artifacts from pipeline state or glob
fallback, generates a self-contained HTML summary and DEMO.md narrative, and copies all
relevant files into demo/<client>/<ep_id>/.
"""

import base64
import json
import shutil
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Optional

from jinja2 import Environment, FileSystemLoader

from audio_processor import _parse_loudnorm_json
from client_config import activate_client
from config import Config
from logger import logger
from outreach_tracker import OutreachTracker
from pipeline import run_with_notification
from pipeline_state import PipelineState
from pitch_generator import PitchGenerator

# ---------------------------------------------------------------------------
# DEMO.md template
# ---------------------------------------------------------------------------

_DEMO_MD_TEMPLATE = """# Demo: {episode_title}

**Client:** {client_name}
**Episode:** {episode_id}
**Processed:** {processed_date}

## What Was Automated

| Step | Tool | What Happened |
|------|------|---------------|
| Transcription | Whisper (local, GPU) | Full episode transcript with word-level timestamps |
| Content Analysis | GPT-4o | Episode summary, show notes, social captions, chapter markers, clip selection |
| Censorship | FFmpeg duck-fade | {censor_count} segments silenced with smooth volume duck |
| Audio Mastering | FFmpeg loudnorm EBU R128 | {lufs_input} LUFS → {lufs_output} LUFS (target: -16 LUFS) |
| Clip Extraction | pydub + FFmpeg | {clip_count} clips selected by energy scoring |
| Caption Overlays | FFmpeg + pysubs2 | Word-by-word Hormozi-style captions burned into vertical MP4s |
| Thumbnail | Pillow | 1280×720 episode thumbnail generated |
| Compliance Check | GPT-4o | {compliance_critical} critical flags, {compliance_warning} warnings |

## Estimated Time Saved

| Task | Manual (editor) | Automated |
|------|-----------------|-----------|
| Transcription | 2-3 hours | ~20 minutes (Whisper GPU) |
| Show notes + captions | 1-2 hours | ~2 minutes (GPT-4o) |
| Audio mastering | 30-60 minutes | ~5 minutes (FFmpeg) |
| Clip selection + subtitles | 2-4 hours | ~10 minutes |
| Thumbnail | 30-60 minutes | ~1 minute |
| **Total** | **6-11 hours** | **~38 minutes** |

## Cost Per Episode

- OpenAI GPT-4o: ~$0.50-1.50 (analysis + compliance)
- Local Whisper: $0 (GPU, electricity only)
- FFmpeg processing: $0
- **Total: ~$1-2 per episode**

## Before/After Audio

{before_after_section}

## Audio Metrics

| Metric | Value |
|--------|-------|
| Input LUFS | {lufs_input} |
| Output LUFS | {lufs_output} |
| Censored Segments | {censor_count} |

## Top Clips (by energy score)

{clip_list}

## Compliance Summary

{compliance_summary}

---

*Generated by Podcast Automation Pipeline*
"""

_BEFORE_AFTER_PRESENT = """See `before_after/` folder:
- `raw_60s.wav` — raw recorded audio (unmastered, uncensored)
- `processed_60s.wav` — same segment after mastering

Timestamp: {snapshot_start:.0f}s – {snapshot_end:.0f}s of episode"""

_BEFORE_AFTER_ABSENT = "No raw snapshot available for this episode."


class DemoPackager:
    """Assembles existing pipeline output into a presentable sales demo folder.

    Read-only: discovers artifacts, copies them, and generates DEMO.md and
    summary.html. Never calls OpenAI, Whisper, or any pipeline component.
    """

    def __init__(self):
        """Initialize DemoPackager. Always enabled — no credentials needed."""
        self.enabled = True
        templates_dir = Path(__file__).parent / "templates"
        self._jinja_env = Environment(
            loader=FileSystemLoader(str(templates_dir)),
            autoescape=True,
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def package_demo(self, client_name: str, episode_id: str) -> Path:
        """Assemble pipeline output into a demo folder.

        Args:
            client_name: Client slug (e.g., 'true-crime-client').
            episode_id: Episode identifier (e.g., 'ep_399').

        Returns:
            Path to the created demo folder.
        """
        logger.info("Packaging demo for %s / %s", client_name, episode_id)

        # Derive paths from current Config (caller should have activated client)
        ep_dir = Config.OUTPUT_DIR / episode_id
        clips_source_dir = Config.CLIPS_DIR / client_name / episode_id
        demo_dir = Config.BASE_DIR / "demo" / client_name / episode_id

        demo_dir.mkdir(parents=True, exist_ok=True)
        (demo_dir / "clips").mkdir(exist_ok=True)

        # --- Load pipeline state (for accurate artifact paths) ---
        state = PipelineState(episode_id)

        # --- Discover artifacts ---
        analysis, analysis_path = self._find_analysis(ep_dir, state)
        if analysis is None:
            raise FileNotFoundError(
                f"No analysis JSON found in {ep_dir}. Run the pipeline first."
            )

        wav_path = self._find_wav(ep_dir, state)
        mp3_path = self._find_mp3(ep_dir, state)
        thumbnail_path = self._find_thumbnail(ep_dir)
        compliance_data, compliance_path = self._find_compliance(ep_dir)
        raw_snapshot_path = self._find_raw_snapshot(ep_dir, state)
        clip_paths = self._find_clips(clips_source_dir, state)
        if not clip_paths:
            clip_paths = self._find_clips(ep_dir / "clips", state)

        # --- Copy artifacts ---
        skipped = []

        # MP3
        if mp3_path and mp3_path.exists():
            shutil.copy2(mp3_path, demo_dir / "processed_audio.mp3")
            logger.info("Copied processed audio: %s", mp3_path.name)
        else:
            skipped.append("processed_audio.mp3")
            logger.warning("No processed MP3 found — skipping processed_audio.mp3")

        # Thumbnail
        if thumbnail_path and thumbnail_path.exists():
            shutil.copy2(thumbnail_path, demo_dir / "thumbnail.png")
            logger.info("Copied thumbnail: %s", thumbnail_path.name)
        else:
            skipped.append("thumbnail.png")
            logger.warning("No thumbnail found — skipping thumbnail.png")

        # Compliance
        if compliance_path and compliance_path.exists():
            shutil.copy2(compliance_path, demo_dir / "compliance_report.json")
            logger.info("Copied compliance report")

        # Clips
        copied_clips = 0
        if clip_paths:
            for i, clip in enumerate(sorted(clip_paths), start=1):
                dest = demo_dir / "clips" / f"clip_{i:02d}.mp4"
                shutil.copy2(clip, dest)
                copied_clips += 1
            logger.info("Copied %d clips", copied_clips)
        else:
            logger.warning("No clip videos found — clips/ folder will be empty")

        # --- Generate captions.txt ---
        captions = analysis.get("social_captions", {})
        self._write_captions(demo_dir, captions)

        # --- Generate show_notes.txt ---
        show_notes = analysis.get("show_notes", "")
        (demo_dir / "show_notes.txt").write_text(show_notes, encoding="utf-8")

        # --- Before/after audio ---
        snapshot_start = 0.0
        has_before_after = False
        if raw_snapshot_path and raw_snapshot_path.exists():
            before_after_dir = demo_dir / "before_after"
            before_after_dir.mkdir(exist_ok=True)
            shutil.copy2(raw_snapshot_path, before_after_dir / "raw_60s.wav")
            logger.info("Copied raw snapshot for before/after")

            # Extract processed 60s from same window
            snapshot_start = (analysis.get("best_clips") or [{}])[0].get(
                "start_seconds", 60.0
            )
            snapshot_end = snapshot_start + 60.0
            processed_src = wav_path if wav_path and wav_path.exists() else mp3_path
            if processed_src and processed_src.exists():
                processed_60s = before_after_dir / "processed_60s.wav"
                self._extract_audio_segment(
                    processed_src, snapshot_start, snapshot_end, processed_60s
                )
                if processed_60s.exists():
                    has_before_after = True
        else:
            logger.info("No raw snapshot found — skipping before_after/")

        # --- Measure LUFS ---
        measure_src = wav_path if wav_path and wav_path.exists() else mp3_path
        lufs_stats = {}
        if measure_src and measure_src.exists():
            lufs_stats = self._measure_lufs(measure_src)

        lufs_input = lufs_stats.get("input_i", "N/A")
        lufs_output = lufs_stats.get("output_i", "N/A")

        # --- Build compliance summary strings ---
        compliance_critical = False
        compliance_flagged_count = 0
        compliance_warning_count = 0
        if compliance_data:
            compliance_critical = compliance_data.get("critical", False)
            compliance_flagged_count = len(compliance_data.get("flagged", []))
            compliance_warning_count = len(compliance_data.get("warnings", []))

        # --- Generate DEMO.md ---
        censor_count = len(analysis.get("censor_timestamps", []))
        clip_list = self._format_clip_list(analysis.get("best_clips", []))
        compliance_summary = self._format_compliance_summary(
            compliance_data, compliance_critical, compliance_flagged_count
        )

        before_after_section = (
            _BEFORE_AFTER_PRESENT.format(
                snapshot_start=snapshot_start,
                snapshot_end=snapshot_start + 60.0,
            )
            if has_before_after
            else _BEFORE_AFTER_ABSENT
        )

        demo_md = _DEMO_MD_TEMPLATE.format(
            episode_title=analysis.get("episode_title", episode_id),
            client_name=client_name,
            episode_id=episode_id,
            processed_date=datetime.now().strftime("%Y-%m-%d"),
            censor_count=censor_count,
            lufs_input=lufs_input,
            lufs_output=lufs_output,
            clip_count=copied_clips,
            compliance_critical="Yes" if compliance_critical else "No",
            compliance_warning=compliance_warning_count,
            before_after_section=before_after_section,
            clip_list=clip_list,
            compliance_summary=compliance_summary,
        )
        (demo_dir / "DEMO.md").write_text(demo_md, encoding="utf-8")
        logger.info("Generated DEMO.md")

        # --- Generate summary.html ---
        thumbnail_b64 = ""
        if thumbnail_path and thumbnail_path.exists():
            with open(thumbnail_path, "rb") as f:
                thumbnail_b64 = base64.b64encode(f.read()).decode()

        template = self._jinja_env.get_template("demo_summary.html.j2")
        html = template.render(
            client_name=client_name,
            episode_id=episode_id,
            episode_title=analysis.get("episode_title", episode_id),
            episode_summary=analysis.get("episode_summary", ""),
            thumbnail_b64=thumbnail_b64,
            best_clips=analysis.get("best_clips", []),
            social_captions=captions,
            show_notes=analysis.get("show_notes", ""),
            chapters=analysis.get("chapters", []),
            lufs_input=lufs_input,
            lufs_output=lufs_output,
            censor_count=censor_count,
            clip_count=copied_clips,
            compliance_checked=compliance_data is not None,
            compliance_critical=compliance_critical,
            compliance_flagged_count=compliance_flagged_count,
            generated_at=datetime.now().strftime("%Y-%m-%d %H:%M UTC"),
        )
        (demo_dir / "summary.html").write_text(html, encoding="utf-8")
        logger.info("Generated summary.html")

        # --- Summary report ---
        print(f"\n{'=' * 60}")
        print(f"Demo packaged: {demo_dir}")
        print(f"  Clips: {copied_clips}")
        print(f"  LUFS: {lufs_input} -> {lufs_output}")
        print(f"  Censor segments: {censor_count}")
        if skipped:
            print(f"  Skipped (not found): {', '.join(skipped)}")
        print(f"{'=' * 60}\n")

        return demo_dir

    # ------------------------------------------------------------------
    # LUFS measurement
    # ------------------------------------------------------------------

    def _measure_lufs(self, audio_path: Path) -> dict:
        """Measure LUFS via FFmpeg loudnorm pass 1.

        Args:
            audio_path: Path to audio file to measure.

        Returns:
            Dict with input_i, output_i, etc., or empty dict on failure.
        """
        cmd = [
            Config.FFMPEG_PATH,
            "-i",
            str(audio_path),
            "-af",
            "loudnorm=I=-16:LRA=11:TP=-1.5:print_format=json",
            "-f",
            "null",
            "-",
        ]
        try:
            result = subprocess.run(
                cmd,
                stderr=subprocess.PIPE,
                text=True,
                check=False,
                stdin=subprocess.DEVNULL,
                timeout=120,
            )
            return _parse_loudnorm_json(result.stderr)
        except Exception as e:
            logger.warning("LUFS measurement failed for %s: %s", audio_path.name, e)
            return {}

    # ------------------------------------------------------------------
    # Artifact discovery helpers
    # ------------------------------------------------------------------

    def _find_analysis(
        self, ep_dir: Path, state: PipelineState
    ) -> tuple[Optional[dict], Optional[Path]]:
        """Find and parse the analysis JSON.

        Returns:
            (analysis_dict, path) or (None, None) if not found.
        """
        path = None
        if state.is_step_completed("analyze"):
            outputs = state.get_step_outputs("analyze")
            candidate = Path(outputs.get("analysis_path", ""))
            if candidate.exists():
                path = candidate

        if path is None:
            # Fallback: newest by mtime
            candidates = sorted(
                ep_dir.glob("*_analysis.json"),
                key=lambda p: p.stat().st_mtime,
            )
            if candidates:
                path = candidates[-1]

        if path is None:
            return None, None

        try:
            with open(path, "r", encoding="utf-8") as f:
                return json.load(f), path
        except Exception as e:
            logger.warning("Failed to read analysis JSON %s: %s", path, e)
            return None, None

    def _find_wav(self, ep_dir: Path, state: PipelineState) -> Optional[Path]:
        """Find the normalized/censored WAV file."""
        if state.is_step_completed("normalize"):
            outputs = state.get_step_outputs("normalize")
            p = Path(outputs.get("normalized_audio", ""))
            if p.exists():
                return p

        if state.is_step_completed("censor"):
            outputs = state.get_step_outputs("censor")
            p = Path(outputs.get("censored_audio", ""))
            if p.exists():
                return p

        # Fallback glob
        candidates = sorted(
            ep_dir.glob("*_censored.wav"),
            key=lambda p: p.stat().st_mtime,
        )
        return candidates[-1] if candidates else None

    def _find_mp3(self, ep_dir: Path, state: PipelineState) -> Optional[Path]:
        """Find the processed MP3 file."""
        if state.is_step_completed("convert_mp3"):
            outputs = state.get_step_outputs("convert_mp3")
            p = Path(outputs.get("mp3_path", ""))
            if p.exists():
                return p

        candidates = sorted(
            ep_dir.glob("*_censored.mp3"),
            key=lambda p: p.stat().st_mtime,
        )
        return candidates[-1] if candidates else None

    def _find_thumbnail(self, ep_dir: Path) -> Optional[Path]:
        """Find the episode thumbnail PNG."""
        candidates = sorted(
            ep_dir.glob("*_thumbnail.png"),
            key=lambda p: p.stat().st_mtime,
        )
        return candidates[-1] if candidates else None

    def _find_compliance(self, ep_dir: Path) -> tuple[Optional[dict], Optional[Path]]:
        """Find the newest compliance report JSON.

        Returns:
            (compliance_dict, path) or (None, None) if not found.
        """
        candidates = sorted(
            ep_dir.glob("compliance_report_*.json"),
            key=lambda p: p.stat().st_mtime,
        )
        if not candidates:
            return None, None

        path = candidates[-1]
        try:
            with open(path, "r", encoding="utf-8") as f:
                return json.load(f), path
        except Exception as e:
            logger.warning("Failed to read compliance JSON %s: %s", path, e)
            return None, None

    def _find_raw_snapshot(self, ep_dir: Path, state: PipelineState) -> Optional[Path]:
        """Find the raw audio snapshot from pipeline state or glob fallback."""
        if state.is_step_completed("censor"):
            outputs = state.get_step_outputs("censor")
            raw = outputs.get("raw_snapshot_path")
            if raw:
                p = Path(raw)
                if p.exists():
                    return p

        # Fallback: glob for snapshot file
        candidates = sorted(
            ep_dir.glob("*_raw_snapshot.wav"),
            key=lambda p: p.stat().st_mtime,
        )
        return candidates[-1] if candidates else None

    def _find_clips(self, clips_source_dir: Path, state: PipelineState) -> list[Path]:
        """Find clip MP4 files from pipeline state or glob fallback."""
        if state.is_step_completed("convert_videos"):
            outputs = state.get_step_outputs("convert_videos")
            paths = outputs.get("video_clip_paths", [])
            existing = [Path(p) for p in paths if Path(p).exists()]
            if existing:
                return existing

        # Fallback: glob clip MP4s (subtitle clips or video-source clips)
        if not clips_source_dir.exists():
            return []
        clips = sorted(clips_source_dir.glob("*_subtitle.mp4"))
        if not clips:
            clips = sorted(clips_source_dir.glob("*_video.mp4"))
        return clips

    # ------------------------------------------------------------------
    # Content generation helpers
    # ------------------------------------------------------------------

    def _write_captions(self, demo_dir: Path, captions: dict) -> None:
        """Write all platform captions to captions.txt."""
        lines = []
        for platform in ("youtube", "instagram", "twitter", "tiktok"):
            caption = captions.get(platform, "")
            lines.append(f"=== {platform.upper()} ===\n")
            lines.append(caption)
            lines.append("\n\n")
        (demo_dir / "captions.txt").write_text("".join(lines).strip(), encoding="utf-8")

    def _extract_audio_segment(
        self,
        src: Path,
        start_s: float,
        end_s: float,
        dest: Path,
    ) -> None:
        """Extract a time segment from audio using FFmpeg subprocess.

        Args:
            src: Source audio file.
            start_s: Start time in seconds.
            end_s: End time in seconds.
            dest: Output WAV path.
        """
        cmd = [
            Config.FFMPEG_PATH,
            "-i",
            str(src),
            "-ss",
            str(start_s),
            "-to",
            str(end_s),
            "-acodec",
            "pcm_s16le",
            "-ar",
            "44100",
            "-y",
            str(dest),
        ]
        try:
            subprocess.run(
                cmd,
                stderr=subprocess.DEVNULL,
                stdin=subprocess.DEVNULL,
                check=True,
                timeout=600,
            )
            logger.info("Extracted processed segment: %s", dest.name)
        except Exception as e:
            logger.warning("Failed to extract processed segment: %s", e)

    def _format_clip_list(self, best_clips: list) -> str:
        """Format best_clips list as markdown bullet points."""
        if not best_clips:
            return "No clips available."
        lines = []
        for i, clip in enumerate(best_clips, start=1):
            title = clip.get("suggested_title", f"Clip {i}")
            desc = clip.get("description", "")
            start = clip.get("start_seconds", 0)
            end = clip.get("end_seconds", 0)
            lines.append(f"{i}. **{title}** ({int(start)}s–{int(end)}s): {desc}")
        return "\n".join(lines)

    def _format_compliance_summary(
        self,
        compliance_data: Optional[dict],
        critical: bool,
        flagged_count: int,
    ) -> str:
        """Format compliance data as a markdown summary string."""
        if compliance_data is None:
            return "No compliance report available."
        status = "CRITICAL" if critical else "PASS"
        return (
            f"Status: **{status}**\n"
            f"Flagged segments: {flagged_count}\n"
            f"Warnings: {len(compliance_data.get('warnings', []))}"
        )


# ---------------------------------------------------------------------------
# Standalone workflow orchestration
# ---------------------------------------------------------------------------


def run_demo_workflow(
    slug: str,
    episode_id: str,
    args: dict,
    consent_fn=None,
) -> Optional[Path]:
    """Consent-gated demo workflow: process episode, package demo, generate pitch.

    Args:
        slug: Prospect slug matching the outreach tracker entry.
        episode_id: Episode identifier (e.g., 'ep01').
        args: Pipeline args dict (test_mode, dry_run, auto_approve, resume, etc.).
        consent_fn: Optional callable that receives a prompt string and returns the
            user's response. When None, ``input()`` is used. Inject for testing.

    Returns:
        Path to the demo folder if workflow completes successfully, None if aborted.

    Raises:
        ValueError: If prospect slug is not found in the outreach tracker.
    """
    tracker = OutreachTracker()
    prospect = tracker.get_prospect(slug)
    if prospect is None:
        raise ValueError(f"Prospect '{slug}' not found in tracker")

    show_name = prospect.get("show_name", slug)
    status = prospect.get("status", "unknown")
    contact_email = prospect.get("contact_email", "")

    print(f"\nProspect: {show_name}")
    print(f"  Status: {status}")
    if contact_email:
        print(f"  Contact: {contact_email}")

    prompt = (
        f"CONSENT CHECK: Have you obtained explicit permission from the host of "
        f"'{show_name}' to process their episode? Type 'yes' to confirm: "
    )
    if consent_fn is not None:
        response = consent_fn(prompt)
    else:
        response = input(prompt)

    if response.strip().lower() != "yes":
        print("Aborted — no consent confirmed.")
        return None

    # Update tracker: prospect has agreed to a demo
    tracker.update_status(slug, "interested")

    # Activate client config for pipeline context
    activate_client(slug)

    # Run pipeline
    ep_number = int(episode_id.replace("ep", ""))
    run_with_notification(args, episode_number=ep_number)

    # Package demo
    demo_dir = DemoPackager().package_demo(slug, episode_id)

    # Generate pitch (non-fatal — demo folder is the critical output)
    pitch_result = None
    try:
        pitch_result = PitchGenerator().generate_demo_pitch(slug, episode_id)
    except Exception as e:
        logger.warning("Pitch generation failed (non-fatal): %s", e)

    # Update tracker to demo_sent
    tracker.update_status(slug, "demo_sent")

    # Print summary
    print(f"\n{'=' * 60}")
    print("Demo workflow complete!")
    print(f"  Demo folder: {demo_dir}")
    if pitch_result:
        print(f"  Pitch subject: {pitch_result.get('subject', 'N/A')}")
    else:
        print("  Pitch: not generated (see log for details)")
    print("  Next steps: Review the demo output, then send the pitch manually")
    print(f"{'=' * 60}\n")

    return demo_dir


def run_demo_workflow_cli(argv: list, args: dict) -> None:
    """CLI handler for the demo-workflow command.

    Args:
        argv: sys.argv list (slug at index 2, ep_id at index 3).
        args: Parsed flags dict from main.py _parse_flags().
    """
    slug = argv[2] if len(argv) > 2 else None
    ep_id = argv[3] if len(argv) > 3 else None
    if not slug or not ep_id:
        print("Usage: uv run main.py demo-workflow <slug> <ep_id>")
        return
    try:
        run_demo_workflow(slug, ep_id, args)
    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"Error during demo workflow: {e}")
